-- MySQL Script generated by MySQL Workbench
-- Thu Feb  7 13:59:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cemis_recepcao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cemis_recepcao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cemis_recepcao` DEFAULT CHARACTER SET utf8 ;
USE `cemis_recepcao` ;

-- -----------------------------------------------------
-- Table `cemis_recepcao`.`convenio_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cemis_recepcao`.`convenio_tb` (
  `idConvenio` INT(11) NOT NULL AUTO_INCREMENT,
  `convenio` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `obs` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idConvenio`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cemis_recepcao`.`paciente_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cemis_recepcao`.`paciente_tb` (
  `idPaciente` INT(11) NOT NULL AUTO_INCREMENT,
  `nomePaciente` VARCHAR(100) NOT NULL,
  `prontuario` VARCHAR(10) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `rg` VARCHAR(30) NULL DEFAULT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `obs` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `Idx_Paciente_nome` (`nomePaciente` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cemis_recepcao`.`especialidade_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cemis_recepcao`.`especialidade_tb` (
  `idEspecialidade` INT(11) NOT NULL AUTO_INCREMENT,
  `especialidade` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEspecialidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cemis_recepcao`.`profissional_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cemis_recepcao`.`profissional_tb` (
  `idProfissional` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(100) NOT NULL,
  `nomeProfissional` VARCHAR(100) NOT NULL,
  `especialidade` INT(11) NOT NULL,
  `crm` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idProfissional`),
  INDEX `fk_Especialidade_idx` (`especialidade` ASC),
  CONSTRAINT `fk_Especialidade`
    FOREIGN KEY (`especialidade`)
    REFERENCES `cemis_recepcao`.`especialidade_tb` (`idEspecialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cemis_recepcao`.`agenda_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cemis_recepcao`.`agenda_tb` (
  `idAgendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `Profissional` INT(11) NOT NULL,
  `Paciente` INT(11) NOT NULL,
  `Convenio` INT(11) NULL DEFAULT NULL,
  `dataConsulta` DATE NULL DEFAULT NULL,
  `dataAgendamento` DATE NOT NULL,
  `horario` TIME NULL DEFAULT NULL,
  `tipoAgendamento` VARCHAR(2) NOT NULL,
  `status` VARCHAR(2) NOT NULL,
  `valorConsulta` DOUBLE NULL DEFAULT NULL,
  `obs` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idAgendamento`),
  INDEX `fk_Paciente_idx` (`Paciente` ASC),
  INDEX `fk_Profissional_ag_idx` (`Profissional` ASC),
  INDEX `fk_Convenio_idx` (`Convenio` ASC),
  CONSTRAINT `fk_Convenio`
    FOREIGN KEY (`Convenio`)
    REFERENCES `cemis_recepcao`.`convenio_tb` (`idConvenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente`
    FOREIGN KEY (`Paciente`)
    REFERENCES `cemis_recepcao`.`paciente_tb` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Profissional_ag`
    FOREIGN KEY (`Profissional`)
    REFERENCES `cemis_recepcao`.`profissional_tb` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cemis_recepcao`.`horarios_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cemis_recepcao`.`horarios_tb` (
  `idHorarios` INT(11) NOT NULL AUTO_INCREMENT,
  `Medico` INT(11) NOT NULL,
  `diaSemana` INT(11) NOT NULL,
  `inicio` TIME NOT NULL,
  `fim` TIME NOT NULL,
  PRIMARY KEY (`idHorarios`),
  INDEX `fk_Medico_hor_idx` (`Medico` ASC),
  CONSTRAINT `fk_Medico_hor`
    FOREIGN KEY (`Medico`)
    REFERENCES `cemis_recepcao`.`profissional_tb` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
